=pod

=head1 Stashy - an inventory and management tool based on for (R)?ex

Stashy is in a very early development stage. Comments and Suggestions are welcome :)

=head1 Installation

You need (R)?ex, Mojolicious, DM4P and a MySQL Database.

Install (R)?ex from  here L<http://rexify.org/get/>. 

Install Mojolicious via CPAN (see here: L<http://mojolicio.us>).

Install DM4P and DM4P/MySQL from L<https://github.com/krimdomu/dm4p> and L<https://github.com/krimdomu/dm4p-adapter-mysql>.

Clone this repository and edit the file I<lib/Stashy.pm>

 git clone git://github.com/krimdomu/stashy-web.git

Create a mysql database. And create the needed tables I<doc/stashy.sql>.

Edit the file I<stashy.conf>

 {
   db => {
      server   => "localhost",
      schema   => "stashy",
      user     => "stashy",
      password => "stashy",
   },

   rex => {
      user     => "root",
      # private_key => "",
      # public_key  => "",
   },

   scm => {
      checkout_to => "./scm",
   },
 };

Start the Test-Server:

 script/stashy daemon

